### ISSUE TITLE
Options: Menu blank when changing page

### ISSUE THREAD

**Issue by Generalfil** [TarheadStudio/RuinIssues#11]
###### Problem: 
Opening options you get the first tab as expected, change tab, only one option appears (fullscreen), then closing options, and entering options again gives a blank page on every tab

###### Recreate: 
Above

###### Output log:
[output_log.txt](https://github.com/TarheadStudio/RuinIssues/files/947787/output_log.txt)

###### Screenshot:
![image](https://cloud.githubusercontent.com/assets/6750301/25288834/65df345a-26c7-11e7-83ad-81620ea64e7d.png)
![image](https://cloud.githubusercontent.com/assets/6750301/25288846/70a66142-26c7-11e7-92b6-d55a45a90344.png)

![image](https://cloud.githubusercontent.com/assets/6750301/25288704/caa06c34-26c6-11e7-8d2b-8cde6e99938d.png)

**Comment by JiiimmyyN** [comment]
Hopefully solved by tonights test.
If not, please let us know.
