### ISSUE TITLE
Some chat messages gets cut off after the first line

### ISSUE THREAD

**Issue by DennisKrone** [TarheadStudio/RuinIssues#16]
###### Problem: 
Some chat messages gets cut off atfer the first line. The rest is simply not shown

###### Expected Result: 
The full chat message should be shown.

###### Recreate: 
Doesnt seem to happen all the time. Try using the chat during different team setups (alone or against other people).

**Comment by jonwa** [comment]
Thanks for reporting, this bug should now be fixed!
