### ISSUE TITLE
Incorrect Chest Count

### ISSUE THREAD

**Issue by Khaztr** [TarheadStudio/RuinIssues#2]
**Description:**
The main menu indicated that I had 2 Ruin chests and 2 War chests.  After opening a single War chest, it then said I had 2 Ruin chests and 0 War chests.  After opening a single Ruin chest, it then said I had 0 Ruin chests and 0 War chests.

I then received a single chest later on (I believe it was a War chest).  The menu at that point said I had *2* War chests.  Upon opening a single chest, the total went down to 0.

So I believe it was just a cosmetic issue -I was able to open the chests I deserved/earned, but the number was inflated for some reason.

**Comment by JiiimmyyN** [comment]
This should be solved. Thanks for reporting :)
