### ISSUE TITLE
Game crashed in ability picking

### ISSUE THREAD

**Issue by Derivata** [TarheadStudio/RuinIssues#23]
###### Problem: 
The game crashed during the ability picking

###### Expected Result: 
The game should never crash :)

###### Recreate: 
Unknown

###### Output log:
[output_log.txt](https://github.com/TarheadStudio/RuinIssues/files/949105/output_log.txt)

**Comment by Derivata** [comment]
Happened a second time, but this time in the start of the third round.
[output_log.txt](https://github.com/TarheadStudio/RuinIssues/files/949166/output_log.txt)

**Comment by JiiimmyyN** [comment]
We belive this problem has been solved. Closing issue.
