### ISSUE TITLE
Failed to connect to game

### ISSUE THREAD

**Issue by Derivata** [TarheadStudio/RuinIssues#25]
###### Problem: 
During the loading screen my game returned to the main menu.

###### Expected Result: 
A player should enter the game after the loading screen.

###### Output log:
[output_log.txt](https://github.com/TarheadStudio/RuinIssues/files/949127/output_log.txt)

**Comment by JiiimmyyN** [comment]
This issue was due to another player not connecting. (Should show this more clearly!)
