### ISSUE TITLE
Dodge Behavior

### ISSUE THREAD

**Issue by Khaztr** [TarheadStudio/RuinIssues#27]
This may not be a bug, but it is very unexpected behavior IMO.  While pressing S or W (up or down) while pointing the mouse cursor on the opposite end of your character (so above your character if S or below if W), you will dodge (spacebar) in the direction you're moving, NOT the direction of the cursor (so down if S or up if W).  However, the opposite behavior holds true while pressing A or D (left or right).  In those cases, you will dodge (spacebar) in the direction of your cursor, NOT movement.

Let me know if this needs any further clarification.

**Comment by chimchim** [comment]
Could not recreate this behaviour. You always dodge in the current WASD direction
