### ISSUE TITLE
Recieve no game results

### ISSUE THREAD

**Issue by JiiimmyyN** [TarheadStudio/RuinIssues#3]
###### Problem: 
Recieved no game results

###### Expected Result: 
Should recieve game results 

###### Recreate: 
Play a game. First game of the day.

###### Output log:
[output_log.txt](https://github.com/TarheadStudio/RuinIssues/files/947470/output_log.txt)

**Comment by JiiimmyyN** [comment]
[output_log.txt](https://github.com/TarheadStudio/RuinIssues/files/947509/output_log.txt)
Same again

**Comment by joaen** [comment]
[output_log.txt](https://github.com/TarheadStudio/RuinIssues/files/947535/output_log.txt)

Same here
