### ISSUE TITLE
Sometimes i write movement input in the chat

### ISSUE THREAD

**Issue by DennisKrone** [TarheadStudio/RuinIssues#4]
###### Problem: 
I sometimes write random chat messages of random input buttons. This happends after i've written a chat message and closed the chat box.

###### Expected Result: 
I should only write things in the chat when the chat is open.

###### Recreate: 
Try writing a chat message and then leter play a game like normal.

**Comment by Khaztr** [comment]
I experienced this myself in a couple matches, and saw it happen to others.  To clarify, the input commands seem to go through fine, it's just that for some reason they appear to randomly appear in chat, even without ever hitting ENTER.
