### ISSUE TITLE
Duplicate fireball on abilitybar

### ISSUE THREAD

**Issue by jonwa** [TarheadStudio/RuinIssues#5]
###### Problem: 
Wrong abilities on the abilitybar. Blast on first slot was replaces by a second fireball in game.

###### Expected Result: 
 Should have the abilities picked during selection. 

###### Output log:
[output_log.txt](https://github.com/TarheadStudio/RuinIssues/files/947563/output_log.txt)

###### Screenshot:
![ingame](https://cloud.githubusercontent.com/assets/2956076/25285871/0e7f056a-26bc-11e7-8c08-c14a36f63dd2.png)
![selection](https://cloud.githubusercontent.com/assets/2956076/25285898/2dd7d7ac-26bc-11e7-91d6-94f12057c3ec.png)

**Comment by JiiimmyyN** [comment]
Was the blast greyed out in the "Available abilities" bar under the categories.
